#!/bin/sh
changed=0
set_opt() {
  if ! uci -q get "luci.$1" 2>/dev/null; then
    uci set "luci.$1=$2"
    changed=1
  fi
}
set_opt themes.PeDitXOSui /luci-static/peditxosui
set_opt main.mediaurlbase /luci-static/peditxosui
[ $changed = 1 ] && uci commit luci
exit 0
